# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_RCP.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 1280)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        MainWindow.setStyleSheet("background-color:#2C2C2C")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 1280))
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 810, 771, 191))
        self.groupBox_3.setStyleSheet("color:white;font:20px")
        self.groupBox_3.setObjectName("groupBox_3")
        self.displayCamNumber = QtWidgets.QLCDNumber(self.groupBox_3)
        self.displayCamNumber.setGeometry(QtCore.QRect(10, 70, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.displayCamNumber.setFont(font)
        self.displayCamNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.displayCamNumber.setStyleSheet("color :red")
        self.displayCamNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.displayCamNumber.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.displayCamNumber.setMidLineWidth(1)
        self.displayCamNumber.setDigitCount(1)
        self.displayCamNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.displayCamNumber.setProperty("value", 0.0)
        self.displayCamNumber.setProperty("intValue", 0)
        self.displayCamNumber.setObjectName("displayCamNumber")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(180, 40, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(180, 140, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(370, 40, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(370, 140, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 151, 31))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(580, 40, 91, 17))
        self.label_7.setObjectName("label_7")
        self.deco_label = QtWidgets.QLabel(self.groupBox_3)
        self.deco_label.setGeometry(QtCore.QRect(570, 130, 141, 17))
        self.deco_label.setStyleSheet("color:red")
        self.deco_label.setObjectName("deco_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 751, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Camera1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Camera1.setObjectName("Camera1")
        self.horizontalLayout.addWidget(self.Camera1)
        self.Camera2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Camera2.setObjectName("Camera2")
        self.horizontalLayout.addWidget(self.Camera2)
        self.Camera3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Camera3.setObjectName("Camera3")
        self.horizontalLayout.addWidget(self.Camera3)
        self.Camera4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Camera4.setObjectName("Camera4")
        self.horizontalLayout.addWidget(self.Camera4)
        self.Camera5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Camera5.setObjectName("Camera5")
        self.horizontalLayout.addWidget(self.Camera5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 771, 731))
        self.groupBox_2.setStyleSheet("color:white;font:20px")
        self.groupBox_2.setObjectName("groupBox_2")
        self.colorTab = QtWidgets.QTabWidget(self.groupBox_2)
        self.colorTab.setEnabled(True)
        self.colorTab.setGeometry(QtCore.QRect(10, 30, 751, 691))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.colorTab.setFont(font)
        self.colorTab.setObjectName("colorTab")
        self.ColorPage = QtWidgets.QWidget()
        self.ColorPage.setEnabled(True)
        self.ColorPage.setObjectName("ColorPage")
        self.gridLayoutWidget = QtWidgets.QWidget(self.ColorPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 731, 641))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.wb_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.wb_B.setObjectName("wb_B")
        self.trigger = QtWidgets.QPushButton(self.wb_B)
        self.trigger.setGeometry(QtCore.QRect(10, 100, 221, 41))
        self.trigger.setAutoDefault(False)
        self.trigger.setObjectName("trigger")
        self.comboBox = QtWidgets.QComboBox(self.wb_B)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 221, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.wb_B, 2, 1, 1, 1)
        self.gamma_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.gamma_B.setObjectName("gamma_B")
        self.gamma_bar = QtWidgets.QProgressBar(self.gamma_B)
        self.gamma_bar.setGeometry(QtCore.QRect(20, 120, 201, 23))
        self.gamma_bar.setMinimum(-200)
        self.gamma_bar.setMaximum(200)
        self.gamma_bar.setProperty("value", 0)
        self.gamma_bar.setFormat("%v")
        self.gamma_bar.setObjectName("gamma_bar")
        self.gamma_lcd = QtWidgets.QLCDNumber(self.gamma_B)
        self.gamma_lcd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        self.gamma_lcd.setObjectName("gamma_lcd")
        self.gridLayout.addWidget(self.gamma_B, 1, 1, 1, 1)
        self.green_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.green_B.setStyleSheet("background-color:green")
        self.green_B.setObjectName("green_B")
        self.green_bar = QtWidgets.QProgressBar(self.green_B)
        self.green_bar.setGeometry(QtCore.QRect(20, 120, 201, 23))
        self.green_bar.setMinimum(-200)
        self.green_bar.setMaximum(200)
        self.green_bar.setProperty("value", 0)
        self.green_bar.setFormat("%v")
        self.green_bar.setObjectName("green_bar")
        self.green_lcd = QtWidgets.QLCDNumber(self.green_B)
        self.green_lcd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        self.green_lcd.setObjectName("green_lcd")
        self.gridLayout.addWidget(self.green_B, 0, 1, 1, 1)
        self.sat_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.sat_B.setObjectName("sat_B")
        self.sat_bar = QtWidgets.QProgressBar(self.sat_B)
        self.sat_bar.setGeometry(QtCore.QRect(20, 120, 201, 23))
        self.sat_bar.setMinimum(-60)
        self.sat_bar.setMaximum(60)
        self.sat_bar.setProperty("value", 0)
        self.sat_bar.setFormat("%v")
        self.sat_bar.setObjectName("sat_bar")
        self.sat_lcd = QtWidgets.QLCDNumber(self.sat_B)
        self.sat_lcd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        self.sat_lcd.setObjectName("sat_lcd")
        self.gridLayout.addWidget(self.sat_B, 2, 0, 1, 1)
        self.red_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.red_B.setEnabled(True)
        self.red_B.setStyleSheet("background-color:red")
        self.red_B.setCheckable(False)
        self.red_B.setObjectName("red_B")
        self.red_bar = QtWidgets.QProgressBar(self.red_B)
        self.red_bar.setEnabled(True)
        self.red_bar.setGeometry(QtCore.QRect(20, 120, 201, 23))
        self.red_bar.setMinimum(-200)
        self.red_bar.setMaximum(200)
        self.red_bar.setProperty("value", 0)
        self.red_bar.setInvertedAppearance(False)
        self.red_bar.setFormat("%v")
        self.red_bar.setObjectName("red_bar")
        self.red_lcd = QtWidgets.QLCDNumber(self.red_B)
        self.red_lcd.setEnabled(True)
        self.red_lcd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        self.red_lcd.setObjectName("red_lcd")
        self.gridLayout.addWidget(self.red_B, 0, 0, 1, 1)
        self.black_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.black_B.setFont(font)
        self.black_B.setStyleSheet("color:white;")
        self.black_B.setObjectName("black_B")
        self.black_bar = QtWidgets.QProgressBar(self.black_B)
        self.black_bar.setGeometry(QtCore.QRect(20, 120, 201, 23))
        self.black_bar.setMinimum(-30)
        self.black_bar.setMaximum(30)
        self.black_bar.setProperty("value", 0)
        self.black_bar.setFormat("%v")
        self.black_bar.setObjectName("black_bar")
        self.black_lcd = QtWidgets.QLCDNumber(self.black_B)
        self.black_lcd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        self.black_lcd.setObjectName("black_lcd")
        self.gridLayout.addWidget(self.black_B, 1, 0, 1, 1)
        self.sharp_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.sharp_B.setObjectName("sharp_B")
        self.sharp_bar = QtWidgets.QProgressBar(self.sharp_B)
        self.sharp_bar.setGeometry(QtCore.QRect(20, 120, 201, 23))
        self.sharp_bar.setMinimum(-50)
        self.sharp_bar.setMaximum(50)
        self.sharp_bar.setProperty("value", 0)
        self.sharp_bar.setFormat("%v")
        self.sharp_bar.setObjectName("sharp_bar")
        self.sharp_lcd = QtWidgets.QLCDNumber(self.sharp_B)
        self.sharp_lcd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        self.sharp_lcd.setObjectName("sharp_lcd")
        self.gridLayout.addWidget(self.sharp_B, 1, 2, 1, 1)
        self.hue_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.hue_B.setObjectName("hue_B")
        self.hue_bar = QtWidgets.QProgressBar(self.hue_B)
        self.hue_bar.setGeometry(QtCore.QRect(20, 120, 201, 23))
        self.hue_bar.setMinimum(-179)
        self.hue_bar.setMaximum(180)
        self.hue_bar.setProperty("value", 0)
        self.hue_bar.setFormat("%v")
        self.hue_bar.setObjectName("hue_bar")
        self.hue_lcd = QtWidgets.QLCDNumber(self.hue_B)
        self.hue_lcd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        self.hue_lcd.setObjectName("hue_lcd")
        self.gridLayout.addWidget(self.hue_B, 3, 0, 1, 1)
        self.gain_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.gain_B.setObjectName("gain_B")
        self.gain_bar = QtWidgets.QProgressBar(self.gain_B)
        self.gain_bar.setGeometry(QtCore.QRect(20, 120, 201, 23))
        self.gain_bar.setMinimum(-200)
        self.gain_bar.setMaximum(200)
        self.gain_bar.setProperty("value", 0)
        self.gain_bar.setFormat("%v")
        self.gain_bar.setObjectName("gain_bar")
        self.gain_lcd = QtWidgets.QLCDNumber(self.gain_B)
        self.gain_lcd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        self.gain_lcd.setObjectName("gain_lcd")
        self.gridLayout.addWidget(self.gain_B, 2, 2, 1, 1)
        self.ry_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.ry_B.setObjectName("ry_B")
        self.ry_bar = QtWidgets.QProgressBar(self.ry_B)
        self.ry_bar.setGeometry(QtCore.QRect(30, 120, 201, 23))
        self.ry_bar.setMinimum(-200)
        self.ry_bar.setMaximum(200)
        self.ry_bar.setProperty("value", 0)
        self.ry_bar.setFormat("%v")
        self.ry_bar.setObjectName("ry_bar")
        self.ry_lcd = QtWidgets.QLCDNumber(self.ry_B)
        self.ry_lcd.setGeometry(QtCore.QRect(30, 40, 191, 61))
        self.ry_lcd.setObjectName("ry_lcd")
        self.gridLayout.addWidget(self.ry_B, 3, 1, 1, 1)
        self.blue_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.blue_B.setEnabled(True)
        self.blue_B.setStyleSheet("background-color:blue;")
        self.blue_B.setObjectName("blue_B")
        self.blue_bar = QtWidgets.QProgressBar(self.blue_B)
        self.blue_bar.setGeometry(QtCore.QRect(20, 120, 201, 23))
        self.blue_bar.setMinimum(-200)
        self.blue_bar.setMaximum(200)
        self.blue_bar.setProperty("value", 0)
        self.blue_bar.setFormat("%v")
        self.blue_bar.setObjectName("blue_bar")
        self.blue_lcd = QtWidgets.QLCDNumber(self.blue_B)
        self.blue_lcd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.blue_lcd.setFont(font)
        self.blue_lcd.setObjectName("blue_lcd")
        self.gridLayout.addWidget(self.blue_B, 0, 2, 1, 1)
        self.by_B = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.by_B.setObjectName("by_B")
        self.by_bar = QtWidgets.QProgressBar(self.by_B)
        self.by_bar.setGeometry(QtCore.QRect(20, 120, 201, 23))
        self.by_bar.setMinimum(-200)
        self.by_bar.setMaximum(200)
        self.by_bar.setProperty("value", 0)
        self.by_bar.setFormat("%v")
        self.by_bar.setObjectName("by_bar")
        self.by_lcd = QtWidgets.QLCDNumber(self.by_B)
        self.by_lcd.setGeometry(QtCore.QRect(20, 40, 191, 61))
        self.by_lcd.setObjectName("by_lcd")
        self.gridLayout.addWidget(self.by_B, 3, 2, 1, 1)
        self.colorTab.addTab(self.ColorPage, "")
        self.ClipPage = QtWidgets.QWidget()
        self.ClipPage.setObjectName("ClipPage")
        self.colorTab.addTab(self.ClipPage, "")
        self.IpPage = QtWidgets.QWidget()
        self.IpPage.setObjectName("IpPage")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.IpPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 731, 641))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 721, 111))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.main_Combo = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.main_Combo.setObjectName("main_Combo")
        self.horizontalLayout_3.addWidget(self.main_Combo)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 711, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.R1_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.R1_box.setChecked(True)
        self.R1_box.setObjectName("R1_box")
        self.horizontalLayout_4.addWidget(self.R1_box)
        self.R2_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.R2_box.setChecked(True)
        self.R2_box.setObjectName("R2_box")
        self.horizontalLayout_4.addWidget(self.R2_box)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 100, 711, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.M1_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.M1_box.setChecked(True)
        self.M1_box.setObjectName("M1_box")
        self.horizontalLayout_5.addWidget(self.M1_box)
        self.M2_box = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.M2_box.setChecked(True)
        self.M2_box.setObjectName("M2_box")
        self.horizontalLayout_5.addWidget(self.M2_box)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox_7.setSizeIncrement(QtCore.QSize(0, 500))
        self.groupBox_7.setBaseSize(QtCore.QSize(0, 500))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_7)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 711, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.R1_combo = QtWidgets.QComboBox(self.horizontalLayoutWidget_6)
        self.R1_combo.setObjectName("R1_combo")
        self.horizontalLayout_6.addWidget(self.R1_combo)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.R2_combo = QtWidgets.QComboBox(self.horizontalLayoutWidget_6)
        self.R2_combo.setObjectName("R2_combo")
        self.horizontalLayout_6.addWidget(self.R2_combo)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_7)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 110, 711, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.M1_combo = QtWidgets.QComboBox(self.horizontalLayoutWidget_7)
        self.M1_combo.setObjectName("M1_combo")
        self.horizontalLayout_7.addWidget(self.M1_combo)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.M2_combo = QtWidgets.QComboBox(self.horizontalLayoutWidget_7)
        self.M2_combo.setObjectName("M2_combo")
        self.horizontalLayout_7.addWidget(self.M2_combo)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_7)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 70, 711, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.PC1_combo = QtWidgets.QComboBox(self.horizontalLayoutWidget_8)
        self.PC1_combo.setObjectName("PC1_combo")
        self.horizontalLayout_8.addWidget(self.PC1_combo)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.PC2_combo = QtWidgets.QComboBox(self.horizontalLayoutWidget_8)
        self.PC2_combo.setObjectName("PC2_combo")
        self.horizontalLayout_8.addWidget(self.PC2_combo)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 711, 101))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.set_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.set_button.setObjectName("set_button")
        self.horizontalLayout_2.addWidget(self.set_button)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.colorTab.addTab(self.IpPage, "")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 10, 171, 51))
        self.label_6.setStyleSheet("color:white;font:25px")
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 1020, 771, 151))
        self.groupBox.setStyleSheet("color:white;font:20px")
        self.groupBox.setObjectName("groupBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.colorTab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Setting"))
        self.label.setText(_translate("MainWindow", "Iris"))
        self.label_2.setText(_translate("MainWindow", "Black"))
        self.label_3.setText(_translate("MainWindow", "Shutter"))
        self.label_4.setText(_translate("MainWindow", "Gain"))
        self.label_5.setText(_translate("MainWindow", "Active Camera :"))
        self.label_7.setText(_translate("MainWindow", "Auto Iris"))
        self.deco_label.setText(_translate("MainWindow", "Disconnected"))
        self.Camera1.setText(_translate("MainWindow", "Camera 1"))
        self.Camera2.setText(_translate("MainWindow", "Camera 2"))
        self.Camera3.setText(_translate("MainWindow", "Camera 3"))
        self.Camera4.setText(_translate("MainWindow", "Camera 4"))
        self.Camera5.setText(_translate("MainWindow", "Camera 5"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Color Correction"))
        self.wb_B.setTitle(_translate("MainWindow", "White Balance"))
        self.trigger.setText(_translate("MainWindow", "Trigger"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Auto"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Auto"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Manual"))
        self.comboBox.setItemText(2, _translate("MainWindow", "ATWB"))
        self.gamma_B.setTitle(_translate("MainWindow", "Gamma"))
        self.green_B.setTitle(_translate("MainWindow", "Green"))
        self.sat_B.setTitle(_translate("MainWindow", "Saturation"))
        self.red_B.setTitle(_translate("MainWindow", "Red"))
        self.black_B.setTitle(_translate("MainWindow", "Black"))
        self.sharp_B.setTitle(_translate("MainWindow", "Sharp"))
        self.hue_B.setTitle(_translate("MainWindow", "Hue"))
        self.gain_B.setTitle(_translate("MainWindow", "Master Gain"))
        self.ry_B.setTitle(_translate("MainWindow", "R-Y"))
        self.blue_B.setTitle(_translate("MainWindow", "Blue"))
        self.by_B.setTitle(_translate("MainWindow", "B-Y"))
        self.colorTab.setTabText(self.colorTab.indexOf(self.ColorPage), _translate("MainWindow", "Color "))
        self.colorTab.setTabText(self.colorTab.indexOf(self.ClipPage), _translate("MainWindow", "Clip"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Unit Remote Connection"))
        self.label_8.setText(_translate("MainWindow", "Main Device Number :"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Active Device"))
        self.R1_box.setText(_translate("MainWindow", "Robotic 1"))
        self.R2_box.setText(_translate("MainWindow", "Robotic 2"))
        self.M1_box.setText(_translate("MainWindow", "Mini 1 "))
        self.M2_box.setText(_translate("MainWindow", "Mini 2"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Device parameters"))
        self.label_10.setText(_translate("MainWindow", "Robotic 1 "))
        self.label_9.setText(_translate("MainWindow", "Robotic 2"))
        self.label_11.setText(_translate("MainWindow", "Mini 1"))
        self.label_12.setText(_translate("MainWindow", "Mini 2"))
        self.label_13.setText(_translate("MainWindow", "Robotic Cam 1 "))
        self.label_14.setText(_translate("MainWindow", "Robotic Cam 2"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Button"))
        self.set_button.setText(_translate("MainWindow", "Set Parameters"))
        self.pushButton_2.setText(_translate("MainWindow", "Load Parameters"))
        self.colorTab.setTabText(self.colorTab.indexOf(self.IpPage), _translate("MainWindow", "Settings"))
        self.label_6.setText(_translate("MainWindow", "DEEP VISION \n"
"    RCP UNIT "))
        self.groupBox.setTitle(_translate("MainWindow", "Camera Selection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

